### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by jkcpa** [Wndrr/Mjml-CSharp#12]
What specific version of Node are you using? I've experimented with several 10 versions and a couple of 12 versions, and so far all have produced errors (although 10 produces different errors than 12).

**Comment by jkcpa** [comment]
Using Node.js 12.15.0 - here is the error upon running:

internal/modules/cjs/loader.js:1025 throw new ERR_REQUIRE_ESM(filename); ^ Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\JimK.DAYHEATING\Documents\GitHub\Mjml-CSharp\Demo.MvcApp\bin\Release\netcoreapp3.1\Resources\mjmlFromString.mjs at Object.Module._extensions..mjs (internal/modules/cjs/loader.js:1025:9) at Module.load (internal/modules/cjs/loader.js:811:32) at Function.Module._load (internal/modules/cjs/loader.js:723:14) at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) at internal/main/run_main_module.js:17:11 { code: 'ERR_REQUIRE_ESM' }

**Comment by Wndrr** [comment]
The currently installed node version on my dev machine is the v13.7.0 and it runs perfectly.
I haven't touched this project in a while so my memory is a bit faulty, but I don't believe I have tested it with any version other than 13.

Have you tried upgrading node ?
