### ISSUE TITLE
Cannot find module c:\Program

### ISSUE THREAD

**Issue by mwf117** [Wndrr/Mjml-CSharp#15]
Please assist,

Trying to use this package from a c# asp.net REST application, NodeJS v 12.18.4 (latest). 
Have followed the sample code. Receiving this error message in the output when calling mjml.Render:
internal/modules/cjs/loader.js:968
  throw err;
  ^
Error: Cannot find module 'C:\Program'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

Have already tried installing node.js into a path without spaces but this error persists....

**Comment by Wndrr** [comment]
Hmmmm, been a while since I last touched this project, but out of instinct: have you tried installing node.js globally ?
